springdoc:
  api-docs:
    enabled: true # Habilita a documentação OpenAPI
  swagger-ui:
    enabled: true
    url: /v3/api-docs # URL da definição OpenAPI (padrão)
    configUrl: /v3/api-docs/swagger-config # URL da configuração do Swagger UI (padrão)
    path: /swagger-ui # URL para acessar o Swagger UI

server.port: 8081



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: C03lho
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

